AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-pattern-auth-cognito

  This is pattern used to for auth cognito

Globals:
  Function:
    Timeout: 180
    Tracing: Active
    Runtime: nodejs16.x
    MemorySize: 256
    Architectures:
      - x86_64

Parameters:
  CognitoUserPoolArn:
    Description: The ARN of cognito user pool
    Type: String

Resources:
  # REST API
  AppApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: sam-app-pattern2-cognito-rest-api
      Description: Cognito User Pools Authorizer REST API

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/lambda.handler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/lambda.ts

  AuthorizersCognitoUserPools:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      RestApiId: !Ref AppApi
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.authorizationToken
      ProviderARNs:
        - !Ref CognitoUserPoolArn

  # GET Method with Cognito User Pools Authorizer enabled
  MethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AppApi
      ResourceId: !GetAtt AppApi.RootResourceId
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref AuthorizersCognitoUserPools
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ['', ['arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt Function.Arn, '/invocations']]

  # Permission to allow Lambda invocation from API Gateway
  LambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Function
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AppApi}/*/GET/

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - MethodGet
    Properties:
      RestApiId: !Ref AppApi

Outputs:
  AppApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
