AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-pattern-api-gateway-lambda-authorizer

  This is pattern used to create a REST API Gateway with a Lambda Token Authorizer

Globals:
  Function:
    Timeout: 180
    Tracing: Active
    Runtime: nodejs16.x
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        #JWT_SECRET: !Ref JWTSecret
        JWT_SECRET: zozvr7NsMc59TazF3m7WaH22ksvnnzD7
Parameters:
  JWTSecret:
    Description: The secret of authorizer
    Type: String

Resources:
  # REST API
  AppApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: sam-app-api-lambda-authorizer
      Description: Lambda Token Authorizer REST API
      Auth:
        DefaultAuthorizer: RequestAuthorizer
        Authorizers:
          RequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Headers:
                - Authorization

  # # GET Method with Cognito User Pools Authorizer enabled
  # MethodGet:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref AppApi
  #     ResourceId: !GetAtt AppApi.RootResourceId
  #     HttpMethod: GET
  #     AuthorizationType: CUSTOM
  #     AuthorizerId: !Ref AuthorizersLambdaToken
  #     Integration:
  #       Type: AWS_PROXY
  #       IntegrationHttpMethod: POST
  #       Uri: !Join ['', ['arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt Function.Arn, '/invocations']]

  # # Lambda Token Authorizer
  # AuthorizersLambdaToken:
  #   Type: AWS::ApiGateway::Authorizer
  #   Properties:
  #     Name: AuthorizersLambdaToken
  #     Type: TOKEN
  #     RestApiId: !Ref AppApi
  #     IdentitySource: method.request.header.authorizationToken
  #     AuthorizerUri: !Join ['', ['arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt AuthorizerFunction.Arn, '/invocations']]
  
  # Lambda function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/lambda.handler
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref AppApi
            Path: /access
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/lambda.ts
  ApiGetToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getToken.handler
      Events:
        ApiGetTokenEvent:
          Type: Api
          Properties:
            Path: /get-token
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/getToken.ts

  # Authorizer function
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/authorizer.handler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/authorizer.ts

  # Permission to allow Lambda invocation from API Gateway
  ppFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AppApi}/*/GET/

  # Deployment:
  #   Type: AWS::ApiGateway::Deployment
  #   DependsOn:
  #     - MethodGet
  #   Properties:
  #     RestApiId: !Ref AppApi

Outputs:
  AppApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
