AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-api-gateway-lambda-sqs-sns-integration

  This is pattern used to show case integration between API gateway, SNS, SQS, Lambda

Globals:
  Function:
    Timeout: 180
    Tracing: Active
    Runtime: nodejs16.x
    MemorySize: 256
    Architectures:
      - x86_64 

Parameters:
  IntegrationServicesSnsTopicName: #sam-app-apigw-lambda-sqs-sns-integration-sns
    Type: String
  IntegrationServicesSqsQueueName: #sam-app-apigw-lambda-sqs-sns-integration-sqs
    Type: String
  RolesCreation:
    Type: String

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/lambda-api-gateway.handler
      # Role: !GetAtt RolesCreation.Arn
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SamAppSnsTopic  # Using !Ref
      Policies:
        - Statement:
          - Effect: Allow
            Action:
            - sns:Publish
            Resource: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /apigw-lambda-sqs-sns-integration
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: 
          - handlers/lambda-api-gateway.ts

  SqsReceiver:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      Handler: handlers/sqsReceiver.handler
      Role: !Ref RolesCreation
      Events:
        SamAppSQSQueueEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt SamAppSQSQueue.Arn
            BatchSize: 10
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: 
          - handlers/sqsReceiver.ts

  SnsToLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/sns-to-lambda.handler
      Role: !Ref RolesCreation
      Events:
        SamAppSNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SamAppSnsTopic
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: 
          - handlers/sns-to-lambda.ts

  SamAppSnsToLambda:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt SnsToLambdaFunction.Arn
      TopicArn: !Ref SamAppSnsTopic

  SamAppSnsToSqs:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt SamAppSQSQueue.Arn
      TopicArn: !Ref SamAppSnsTopic

  SamAppSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref IntegrationServicesSnsTopicName

  SamAppSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IntegrationServicesSqsQueueName
  
  SamAppSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: 
            - SQS:SendMessage
            - SQS:ReceiveMessage
          Resource: !GetAtt SamAppSQSQueue.Arn
      Queues:
        - !Ref SamAppSQSQueue
